"""
TROJAN REPORT GENERATOR — the sales weapon
==============================================

The heart of the business plan. Instead of cold-pitching a business, you
send them a free, specific, personalized diagnosis of what's costing them
customers right now — generated by running your existing diagnostic
agents together. It looks like ₹15,000 of consulting. It costs you minutes.

This is the "Trojan Horse": a gift so specific the business feels indebted
before you've asked for anything. It's the online version of walking into
a room already knowing more about their situation than they do.

What it runs (all agents you already have):
  - Agent 25 (brand strategy)     -> what type of business, right approach
  - Agent 16 (prediction)         -> realistic cost-per-lead they should expect
  - Agent 30 (SEO audit)          -> concrete website problems (if they have a site)
  - Agent 21 (AI-search visibility)-> do they show up in ChatGPT/Gemini answers

Output: one clean, plain-language report you can paste into WhatsApp/email
or save as a text/HTML file and send. NO jargon — written for a business
owner, not a marketer.

USAGE:
  python3 trojan_report.py --business "Aura Dental Clinic" --niche "dental clinic" \\
      --city "Hyderabad" --website "https://auradental.example.com"

  (website is optional — skip it for businesses with only Instagram)
"""

import os
import sys
import json
import argparse
from datetime import datetime, timezone

# Import the diagnostic agents' functions directly
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

def _safe_import():
    mods = {}
    try:
        import agent_25_brand_strategy as m25; mods["strategy"] = m25
    except Exception as e:
        print(f"[trojan] Could not load brand strategy agent: {e}")
    try:
        import agent_16_prediction_engine as m16; mods["predict"] = m16
    except Exception as e:
        print(f"[trojan] Could not load prediction agent: {e}")
    try:
        import agent_30_seo_suite as m30; mods["seo"] = m30
    except Exception as e:
        print(f"[trojan] Could not load SEO agent: {e}")
    try:
        import agent_21_ai_search_visibility as m21; mods["visibility"] = m21
    except Exception as e:
        print(f"[trojan] Could not load visibility agent: {e}")
    return mods


def generate_report(business, niche, city, website=None, budget=15000):
    mods = _safe_import()
    report = {
        "business": business, "niche": niche, "city": city,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "sections": [],
    }

    # --- 1. Brand strategy (what type of business, right approach) ---
    if "strategy" in mods:
        try:
            desc = f"{business}, a {niche} in {city}"
            classification = mods["strategy"].classify_brand(desc)
            archetype = classification.get("archetype", "unknown")
            playbook = mods["strategy"].PLAYBOOKS.get(archetype, {})
            if playbook:
                report["sections"].append({
                    "title": "What kind of marketing actually fits your business",
                    "body": f"Businesses like yours grow best with: {playbook.get('channels','')}. "
                            f"The single biggest mistake we see {niche}s make: {playbook.get('biggest_mistake','')}",
                })
        except Exception as e:
            print(f"[trojan] strategy section skipped: {e}")

    # --- 2. Cost-per-lead prediction (what to realistically expect) ---
    if "predict" in mods:
        try:
            pred = mods["predict"].predict(niche, city, budget)
            r = pred["predicted_cpl_range"]
            leads = pred["predicted_leads"]
            report["sections"].append({
                "title": "What you should expect to pay for a real enquiry",
                "body": f"For a {niche} in {city}, a realistic cost per genuine enquiry is "
                        f"₹{r['low']}–₹{r['high']}. On a ₹{budget:,}/month budget, that's roughly "
                        f"{leads['low']}–{leads['high']} real enquiries a month. "
                        f"If you're currently paying more than this — or getting fewer — something's off, "
                        f"and it's usually fixable.",
            })
        except Exception as e:
            print(f"[trojan] prediction section skipped: {e}")

    # --- 3. Website audit (concrete problems) — only if they have a site ---
    if website and "seo" in mods:
        try:
            html = mods["seo"].fetch_page(website)
            if html:
                issues, wins = mods["seo"].onpage_audit(html, website)
                high = [msg for sev, msg in issues if sev == "HIGH"]
                if high:
                    body = "We looked at your website and found a few things quietly costing you customers:\n"
                    for msg in high[:3]:
                        body += f"  • {msg}\n"
                    report["sections"].append({
                        "title": "Things on your website losing you customers right now",
                        "body": body.strip(),
                    })
                elif wins:
                    report["sections"].append({
                        "title": "Your website basics",
                        "body": "Good news — your website's basics are in decent shape. "
                                "The bigger opportunity for you is in how you're getting found in the first place.",
                    })
        except Exception as e:
            print(f"[trojan] website section skipped: {e}")

    # --- 4. AI-search visibility (the thing nobody else checks) ---
    if "visibility" in mods and os.environ.get("TAVILY_API_KEY"):
        try:
            query = f"best {niche} in {city}"
            results = mods["visibility"].search_for_query(query)
            if results:
                analysis = mods["visibility"].analyze_visibility(business, query, results)
                rate = analysis["visibility_rate"]
                if rate < 0.3:
                    report["sections"].append({
                        "title": "When people ask AI assistants for a recommendation, do you show up?",
                        "body": f"More and more people now ask ChatGPT or Gemini things like "
                                f"\"{query}\" instead of searching Google. Right now, your business "
                                f"barely shows up in the sources these assistants pull from. This is a "
                                f"brand-new channel almost nobody in your area is thinking about yet — "
                                f"which means it's wide open for you.",
                    })
        except Exception as e:
            print(f"[trojan] visibility section skipped: {e}")

    return report


def render_text(report):
    """Plain-text, WhatsApp/email-ready. No jargon."""
    lines = []
    lines.append(f"Hi {report['business']} team,")
    lines.append("")
    lines.append(f"We took a quick, no-strings look at your {report['niche']} marketing in "
                 f"{report['city']} and pulled together a few honest observations — free, "
                 f"no catch. Hope it's useful either way:")
    lines.append("")
    for i, s in enumerate(report["sections"], 1):
        lines.append(f"{i}. {s['title']}")
        lines.append(f"   {s['body']}")
        lines.append("")
    if not report["sections"]:
        lines.append("(We couldn't pull enough public data to diagnose remotely — but a 10-minute "
                     "chat would let us give you the same honest read.)")
        lines.append("")
    lines.append("If any of this is useful and you'd like us to help fix it, we work month-to-month "
                 "with a live dashboard so you see every rupee and every lead in real time — no lock-in. "
                 "And if not, no worries at all — the notes above are yours to keep.")
    lines.append("")
    lines.append("— Apna Marketer")
    return "\n".join(lines)


def render_html(report):
    """A clean HTML version you can save and send as a proper one-pager."""
    sections_html = ""
    for i, s in enumerate(report["sections"], 1):
        body = s["body"].replace("\n", "<br>")
        sections_html += f"""
        <div style="margin-bottom:22px;">
          <div style="font-size:15px;font-weight:600;color:#E8A33D;margin-bottom:6px;">{i}. {s['title']}</div>
          <div style="font-size:14px;color:#e8e8e8;line-height:1.6;">{body}</div>
        </div>"""

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>A quick look at {report['business']}'s marketing</title></head>
<body style="margin:0;background:#0f1117;font-family:-apple-system,Segoe UI,Roboto,sans-serif;padding:32px 18px;">
<div style="max-width:620px;margin:0 auto;">
  <div style="font-size:13px;color:#8B93A1;letter-spacing:.08em;text-transform:uppercase;margin-bottom:6px;">A free look — no strings</div>
  <div style="font-size:24px;font-weight:700;color:#F1EDE3;margin-bottom:4px;">{report['business']}</div>
  <div style="font-size:14px;color:#8B93A1;margin-bottom:28px;">{report['niche']} · {report['city']}</div>
  {sections_html}
  <div style="border-top:1px solid rgba(255,255,255,.1);margin-top:20px;padding-top:18px;font-size:13px;color:#8B93A1;line-height:1.6;">
    If any of this is useful and you'd like help fixing it, we work month-to-month with a live dashboard —
    you see every rupee and every lead in real time. No lock-in. And if not, these notes are yours to keep.
  </div>
  <div style="font-size:14px;color:#E8A33D;font-weight:600;margin-top:14px;">— Apna Marketer</div>
</div>
</body></html>"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--business", required=True)
    parser.add_argument("--niche", required=True)
    parser.add_argument("--city", required=True)
    parser.add_argument("--website", default=None)
    parser.add_argument("--budget", type=int, default=15000)
    parser.add_argument("--html", action="store_true", help="Also save an HTML one-pager")
    args = parser.parse_args()

    report = generate_report(args.business, args.niche, args.city, args.website, args.budget)

    text = render_text(report)
    print("\n" + "="*60)
    print("TROJAN REPORT — ready to send")
    print("="*60 + "\n")
    print(text)

    # Save text
    safe_name = "".join(c for c in args.business if c.isalnum() or c in " -_").strip().replace(" ", "_")
    txt_path = f"trojan_report_{safe_name}.txt"
    with open(txt_path, "w") as f:
        f.write(text)
    print(f"\n[saved: {txt_path}]")

    if args.html:
        html_path = f"trojan_report_{safe_name}.html"
        with open(html_path, "w") as f:
            f.write(render_html(report))
        print(f"[saved: {html_path}]")
